### ISSUE TITLE
IDE doesn't understand this context inside function

### ISSUE THREAD

**Issue by intellix** [zhaosiyang/property-watch-decorator#1]
Nice talk at ng-conf. Was quite interested to try this as it'd help clean up the getter/setter proxy function boilerplate I've got scattered around my codebase. Not sure if mentioned as a drawback but it seems like VSC doesn't understand the context of this and suddenly you get warnings like unused declarations and not understanding the types of stuff referenced within your component class, as shown here with DomSanitizer:

<img width="591" alt="Screenshot 2019-05-07 13 24 48" src="https://user-images.githubusercontent.com/1162531/57273761-97440480-70cb-11e9-85c2-a9344af0d781.png">

**Comment by zhaosiyang** [comment]
Thanks for your feedback.
You can do this:
```
@OnChange(function(this: IframeComponent, value: any) {...})
```
