### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mbeckenbach** [zhaosiyang/property-watch-decorator#10]
Hi, 

can you please add a licence file to your repository?

**Comment by zhaosiyang** [comment]
Thanks I’ll add an MIT later today. Feel free to use.

**Comment by mbeckenbach** [comment]
Thanks!Am 04.06.2020 15:55 schrieb Siyang Kern Zhao <notifications@github.com>:

Thanks I’ll add an MIT later today. Feel free to use.



On Thu, Jun 4, 2020 at 9:51 AM Max Beckenbach <notifications@github.com>

wrote:

**Comment by zhaosiyang** [comment]
MIT licence added. Thanks for the feedback.
