### ISSUE TITLE
Typescript is complaining by <T = any>

### ISSUE THREAD

**Issue by cdtapay** [zhaosiyang/property-watch-decorator#5]
Typescript version: 3.4.5

**Comment by lppedd** [comment]
@cdtapay what's the warning?

**Comment by zhaosiyang** [comment]
I can't reproduce the warning/error, please provide more detail in a new issue. Thank you.

**Comment by cdtapay** [comment]
Hi sorry for the delay, when I run the project (Angular 2), the console yells at this line:
`export function OnChange<T = any>(callback: (value: T, simpleChange?: SimpleChange<T>) => void) {
`
![image](https://user-images.githubusercontent.com/1795582/59153453-7995f200-8a1f-11e9-9e2b-e944de91c539.png)

![image](https://user-images.githubusercontent.com/1795582/59153472-df827980-8a1f-11e9-903e-2e6142af8ce4.png)

After I removed the `= any`, works fine. I don't know what's hapenning. Thanks.
